[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/dict"
  to = "/.netlify/functions/dictionary"
  status = 200

[[redirects]]
  from = "/api/spellcheck"
  to = "/.netlify/functions/spellcheck"
  status = 200

[[redirects]]
  from = "/api/sync"
  to = "/.netlify/functions/sync"
  status = 200
